// <auto-generated />
using System;
using FJAP.vn.fpt.edu.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FJAP.Migrations
{
    [DbContext(typeof(FjapDbContext))]
    partial class FjapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.HasKey("StudentId", "ClassId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "ClassId" }, "idx_enroll_class");

                    b.HasIndex(new[] { "StudentId" }, "idx_enroll_student");

                    b.ToTable("enrollment", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendance_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Present','Absent','Not Yet')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Present'");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("TimeAttendance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("time_attendance")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AttendanceId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LessonId" }, "idx_att_lesson");

                    b.HasIndex(new[] { "StudentId" }, "idx_att_student");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("class_name");

                    b.Property<int>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("level_id");

                    b.Property<int?>("MaxStudents")
                        .HasColumnType("int")
                        .HasColumnName("max_students");

                    b.Property<int?>("MinStudents")
                        .HasColumnType("int")
                        .HasColumnName("min_students");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("semester_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasDefaultValueSql("'Inactive'");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("ClassId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SubjectId" }, "fk_class_subject1_idx");

                    b.HasIndex(new[] { "LevelId" }, "idx_class_level");

                    b.HasIndex(new[] { "SemesterId" }, "idx_class_semester");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.DailyFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FeedbackTextTranscript")
                        .HasColumnType("longtext");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("DailyFeedbacks");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("department_name");

                    b.HasKey("DepartmentId")
                        .HasName("PRIMARY");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiSuggestions")
                        .HasColumnType("json")
                        .HasColumnName("ai_suggestions")
                        .HasComment("Array các suggestions từ AI (1-3 items)");

                    b.Property<string>("Answers")
                        .HasColumnType("json")
                        .HasColumnName("answers")
                        .HasComment("Map of questionId to answer value (1-4)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id")
                        .HasComment("ID của class được feedback");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FreeText")
                        .HasColumnType("text")
                        .HasColumnName("free_text")
                        .HasComment("Mô tả thêm vấn đề (tối đa 1200 ký tự)");

                    b.Property<string>("FreeTextTranscript")
                        .HasColumnType("text")
                        .HasColumnName("free_text_transcript")
                        .HasComment("Transcript từ speech-to-text (nếu có)");

                    b.Property<string>("IssueCategory")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("issue_category")
                        .HasComment("Category code for feedback issue (e.g., ASSESSMENT_LOAD, FACILITY_ISSUES)");

                    b.Property<string>("Keywords")
                        .HasColumnType("json")
                        .HasColumnName("keywords")
                        .HasComment("Array các keywords từ AI");

                    b.Property<string>("MainIssue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("main_issue")
                        .HasComment("Vấn đề chính được AI phát hiện");

                    b.Property<decimal>("SatisfactionScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("satisfaction_score")
                        .HasComment("0.00 - 1.00");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Positive','Neutral','Negative')")
                        .HasColumnName("sentiment")
                        .HasDefaultValueSql("'Neutral'");

                    b.Property<decimal?>("SentimentScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("sentiment_score")
                        .HasComment("-1.00 đến 1.00");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('New','Reviewed','Actioned')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'New'");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id")
                        .HasComment("ID của student gửi feedback");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id")
                        .HasComment("ID của subject được feedback");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<int>("Urgency")
                        .HasColumnType("int")
                        .HasColumnName("urgency")
                        .HasComment("0-10, urgency >= 7 sẽ gửi notification");

                    b.Property<bool>("WantsOneToOne")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("wants_one_to_one")
                        .HasComment("1 = Có muốn hỗ trợ 1-1, 0 = Không");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassId" }, "idx_feedback_class");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_feedback_created");

                    b.HasIndex(new[] { "Sentiment" }, "idx_feedback_sentiment");

                    b.HasIndex(new[] { "Status" }, "idx_feedback_status");

                    b.HasIndex(new[] { "StudentId" }, "idx_feedback_student");

                    b.HasIndex(new[] { "SubjectId" }, "idx_feedback_subject");

                    b.HasIndex(new[] { "Urgency" }, "idx_feedback_urgency");

                    b.HasIndex(new[] { "IssueCategory" }, "idx_feedbacks_issue_category");

                    b.HasIndex(new[] { "StudentId", "ClassId" }, "uk_feedback_student_class")
                        .IsUnique();

                    b.ToTable("feedbacks", null, t =>
                        {
                            t.HasComment("Bảng lưu feedback của student và kết quả AI analysis");
                        });
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.FeedbackQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerOptions")
                        .HasColumnType("json")
                        .HasColumnName("answer_options")
                        .HasComment("Array of answer options: [{value, label, icon, color}]");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EvaluationLabel")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("evaluation_label");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'")
                        .HasComment("1 = Active, 0 = Inactive");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index")
                        .HasComment("Thứ tự hiển thị (1, 2, 3...)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("question_text")
                        .HasComment("Nội dung câu hỏi");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id")
                        .HasComment("NULL = áp dụng cho tất cả môn, có giá trị = chỉ áp dụng cho môn đó");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IsActive" }, "idx_fq_active");

                    b.HasIndex(new[] { "OrderIndex" }, "idx_fq_order");

                    b.HasIndex(new[] { "SubjectId" }, "idx_fq_subject");

                    b.ToTable("feedback_questions", null, t =>
                        {
                            t.HasComment("Bảng quản lý câu hỏi feedback (Academic Staff có thể tạo/sửa)");
                        });
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("final_score")
                        .HasComment("Điểm tổng kết (tự động tính)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('In Progress',' Passed','Failed')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'In Progress'");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("GradeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StudentId" }, "idx_grade_student");

                    b.HasIndex(new[] { "SubjectId" }, "idx_grade_subject");

                    b.HasIndex(new[] { "StudentId", "SubjectId" }, "uk_student_subject")
                        .IsUnique();

                    b.ToTable("grade", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.GradeType", b =>
                {
                    b.Property<int>("GradeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GradeTypeId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment")
                        .HasComment("Nhận xét của giảng viên");

                    b.Property<int>("GradeId")
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("graded_at");

                    b.Property<int?>("GradedBy")
                        .HasColumnType("int")
                        .HasColumnName("graded_by")
                        .HasComment("Lecturer ID đã chấm");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score")
                        .HasComment("Điểm thực tế của sinh viên");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Pending','Graded','Revised')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<int>("SubjectGradeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("subject_grade_type_id");

                    b.HasKey("GradeTypeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GradeId" }, "idx_gt_grade");

                    b.HasIndex(new[] { "GradedBy" }, "idx_gt_grader");

                    b.HasIndex(new[] { "SubjectGradeTypeId" }, "idx_gt_sgt");

                    b.HasIndex(new[] { "GradeId", "SubjectGradeTypeId" }, "uk_grade_detail")
                        .IsUnique();

                    b.ToTable("grade_type", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("holidayId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date")
                        .HasColumnName("holidayDate");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("holidayName");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("semesterId");

                    b.HasKey("HolidayId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "HolidayDate" }, "idx_holiday_date");

                    b.HasIndex(new[] { "SemesterId" }, "idx_holiday_semester");

                    b.HasIndex(new[] { "SemesterId", "HolidayDate" }, "idx_holiday_semester_date");

                    b.ToTable("holiday", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Homework", b =>
                {
                    b.Property<int>("HomeworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("homework_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HomeworkId"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime")
                        .HasColumnName("deadline");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_path");

                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("HomeworkId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LessonId" }, "idx_homework_lesson");

                    b.ToTable("homework", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.HomeworkSubmission", b =>
                {
                    b.Property<int>("HomeworkSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("homework_submission_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HomeworkSubmissionId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_path");

                    b.Property<int>("HomeworkId")
                        .HasColumnType("int")
                        .HasColumnName("homework_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Submitted','Graded','Late','Rejected')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Submitted'");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("HomeworkSubmissionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "HomeworkId" }, "idx_hws_homework");

                    b.HasIndex(new[] { "StudentId" }, "idx_hws_student");

                    b.ToTable("homework_submission", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Lecture", b =>
                {
                    b.Property<int>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lecture_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LectureId"));

                    b.Property<string>("LecturerCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lecturer_code");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LectureId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "idx_lecture_user");

                    b.ToTable("lecture", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("LectureId")
                        .HasColumnType("int")
                        .HasColumnName("lecture_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<int>("TimeId")
                        .HasColumnType("int")
                        .HasColumnName("time_id");

                    b.HasKey("LessonId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassId" }, "idx_lesson_class");

                    b.HasIndex(new[] { "LectureId" }, "idx_lesson_lecture");

                    b.HasIndex(new[] { "RoomId" }, "idx_lesson_room");

                    b.HasIndex(new[] { "TimeId" }, "idx_lesson_time");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("level_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("level_name");

                    b.HasKey("LevelId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LevelName" }, "uk_level_name")
                        .IsUnique();

                    b.ToTable("level", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('active','inActive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("MaterialId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedBy" }, "fk_material_created_by");

                    b.HasIndex(new[] { "UpdatedBy" }, "fk_material_updated_by");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_material_created_at");

                    b.HasIndex(new[] { "Status" }, "idx_material_status");

                    b.HasIndex(new[] { "SubjectId" }, "idx_material_subject");

                    b.ToTable("material", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("NewsImage")
                        .HasColumnType("longtext")
                        .HasColumnName("news_image");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("text")
                        .HasColumnName("review_comment");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('draft','pending','published','rejected')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'draft'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ApprovedBy" }, "fk_news_approved_by");

                    b.HasIndex(new[] { "CreatedBy" }, "fk_news_created_by");

                    b.HasIndex(new[] { "UpdatedBy" }, "fk_news_updated_by");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "idx_notif_user");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleName" }, "uk_role_name")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("room_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("RoomId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoomName" }, "uk_room_name")
                        .IsUnique();

                    b.ToTable("room", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("semester_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("SemesterCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("semester_code")
                        .HasDefaultValueSql("''");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("SemesterId")
                        .HasName("PRIMARY");

                    b.ToTable("semester", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date");

                    b.Property<int>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("level_id");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("semester_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("student_code");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("StudentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LevelId" }, "idx_student_level");

                    b.HasIndex(new[] { "SemesterId" }, "idx_student_semester");

                    b.HasIndex(new[] { "UserId" }, "idx_student_user");

                    b.HasIndex(new[] { "StudentCode" }, "uk_student_code")
                        .IsUnique();

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("level_id");

                    b.Property<decimal?>("PassMark")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("pass_mark")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("subject_code");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subject_name");

                    b.Property<int>("TotalLesson")
                        .HasColumnType("int")
                        .HasColumnName("total_lesson");

                    b.HasKey("SubjectId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LevelId" }, "idx_subject_level");

                    b.HasIndex(new[] { "SubjectCode" }, "uk_subject_code")
                        .IsUnique();

                    b.ToTable("subject", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_croatian_ci");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.SubjectGradeType", b =>
                {
                    b.Property<int>("SubjectGradeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subject_grade_type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubjectGradeTypeId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasComment("Manager ID tạo cấu hình");

                    b.Property<string>("GradeTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("grade_type_name")
                        .HasComment("Quiz, Assignment, Midterm, Final, etc.");

                    b.Property<decimal>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("max_score")
                        .HasDefaultValueSql("'10.00'")
                        .HasComment("Điểm tối đa (thường là 10)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight")
                        .HasComment("Tỷ trọng % (0-100)");

                    b.HasKey("SubjectGradeTypeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SubjectId" }, "idx_sgt_subject");

                    b.HasIndex(new[] { "SubjectId", "GradeTypeName" }, "uk_subject_grade_type")
                        .IsUnique();

                    b.ToTable("subject_grade_type", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Timeslot", b =>
                {
                    b.Property<int>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("time_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TimeId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("TimeId")
                        .HasName("PRIMARY");

                    b.ToTable("timeslot", (string)null);
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("enum('Male','Female','Other')")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DepartmentId" }, "fk_user_department1_idx");

                    b.HasIndex(new[] { "RoleId" }, "idx_user_role");

                    b.HasIndex(new[] { "Email" }, "uk_user_email")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "uk_user_phone")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Enrollment", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_class");

                    b.HasOne("FJAP.vn.fpt.edu.models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_student");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Attendance", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Lesson", "Lesson")
                        .WithMany("Attendances")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_lesson");

                    b.HasOne("FJAP.vn.fpt.edu.models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_student");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Class", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Level", "Level")
                        .WithMany("Classes")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("fk_class_level");

                    b.HasOne("FJAP.vn.fpt.edu.models.Semester", "Semester")
                        .WithMany("Classes")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("fk_class_semester");

                    b.HasOne("FJAP.vn.fpt.edu.models.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("fk_class_subject1");

                    b.Navigation("Level");

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.DailyFeedback", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FJAP.vn.fpt.edu.models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FJAP.vn.fpt.edu.models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FJAP.vn.fpt.edu.models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Feedback", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Class", "Class")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_class");

                    b.HasOne("FJAP.vn.fpt.edu.models.Student", "Student")
                        .WithMany("Feedbacks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_student");

                    b.HasOne("FJAP.vn.fpt.edu.models.Subject", "Subject")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_subject");

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.FeedbackQuestion", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Subject", "Subject")
                        .WithMany("FeedbackQuestions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_feedback_question_subject");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Grade", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grade_student");

                    b.HasOne("FJAP.vn.fpt.edu.models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grade_subject");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.GradeType", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Grade", "Grade")
                        .WithMany("GradeTypes")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grade_type_grade");

                    b.HasOne("FJAP.vn.fpt.edu.models.SubjectGradeType", "SubjectGradeType")
                        .WithMany("GradeTypes")
                        .HasForeignKey("SubjectGradeTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_grade_type_sgt");

                    b.Navigation("Grade");

                    b.Navigation("SubjectGradeType");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Holiday", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Semester", "Semester")
                        .WithMany("Holidays")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("holiday_ibfk_1");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Homework", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Lesson", "Lesson")
                        .WithMany("Homeworks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homework_lesson");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.HomeworkSubmission", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Homework", "Homework")
                        .WithMany("HomeworkSubmissions")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hws_homework");

                    b.HasOne("FJAP.vn.fpt.edu.models.Student", "Student")
                        .WithMany("HomeworkSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hws_student");

                    b.Navigation("Homework");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Lecture", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.User", "User")
                        .WithMany("Lectures")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_lecture_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Lesson", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Class", "Class")
                        .WithMany("Lessons")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("fk_lesson_class");

                    b.HasOne("FJAP.vn.fpt.edu.models.Lecture", "Lecture")
                        .WithMany("Lessons")
                        .HasForeignKey("LectureId")
                        .IsRequired()
                        .HasConstraintName("fk_lesson_lecture");

                    b.HasOne("FJAP.vn.fpt.edu.models.Room", "Room")
                        .WithMany("Lessons")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("fk_lesson_room");

                    b.HasOne("FJAP.vn.fpt.edu.models.Timeslot", "Time")
                        .WithMany("Lessons")
                        .HasForeignKey("TimeId")
                        .IsRequired()
                        .HasConstraintName("fk_lesson_timeslot");

                    b.Navigation("Class");

                    b.Navigation("Lecture");

                    b.Navigation("Room");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Material", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.User", "CreatedByNavigation")
                        .WithMany("MaterialCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_material_created_by");

                    b.HasOne("FJAP.vn.fpt.edu.models.Subject", "Subject")
                        .WithMany("Materials")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("fk_material_subject");

                    b.HasOne("FJAP.vn.fpt.edu.models.User", "UpdatedByNavigation")
                        .WithMany("MaterialUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_material_updated_by");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Subject");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.News", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.User", "ApprovedByNavigation")
                        .WithMany("NewsApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_news_approved_by");

                    b.HasOne("FJAP.vn.fpt.edu.models.User", "CreatedByNavigation")
                        .WithMany("NewsCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_news_created_by");

                    b.HasOne("FJAP.vn.fpt.edu.models.User", "UpdatedByNavigation")
                        .WithMany("NewsUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_news_updated_by");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Notification", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_notifications_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Student", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Level", "Level")
                        .WithMany("Students")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("fk_student_level");

                    b.HasOne("FJAP.vn.fpt.edu.models.Semester", "Semester")
                        .WithMany("Students")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_student_semester");

                    b.HasOne("FJAP.vn.fpt.edu.models.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_student_user");

                    b.Navigation("Level");

                    b.Navigation("Semester");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Subject", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Level", "Level")
                        .WithMany("Subjects")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("fk_subject_level");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.SubjectGradeType", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Subject", "Subject")
                        .WithMany("SubjectGradeTypes")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sgt_subject");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.User", b =>
                {
                    b.HasOne("FJAP.vn.fpt.edu.models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_user_department1");

                    b.HasOne("FJAP.vn.fpt.edu.models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_user_role");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Class", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Grade", b =>
                {
                    b.Navigation("GradeTypes");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Homework", b =>
                {
                    b.Navigation("HomeworkSubmissions");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Lecture", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Lesson", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Homeworks");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Level", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Room", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Semester", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Holidays");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Feedbacks");

                    b.Navigation("Grades");

                    b.Navigation("HomeworkSubmissions");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Subject", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("FeedbackQuestions");

                    b.Navigation("Feedbacks");

                    b.Navigation("Grades");

                    b.Navigation("Materials");

                    b.Navigation("SubjectGradeTypes");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.SubjectGradeType", b =>
                {
                    b.Navigation("GradeTypes");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.Timeslot", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("FJAP.vn.fpt.edu.models.User", b =>
                {
                    b.Navigation("Lectures");

                    b.Navigation("MaterialCreatedByNavigations");

                    b.Navigation("MaterialUpdatedByNavigations");

                    b.Navigation("NewsApprovedByNavigations");

                    b.Navigation("NewsCreatedByNavigations");

                    b.Navigation("NewsUpdatedByNavigations");

                    b.Navigation("Notifications");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
